import javax.swing.*;
/**
 *
 * @author Dan Boxall
 */
public class CipherUI extends javax.swing.JFrame {
    private Cipher cipher;

    /**
     * Creates new form CipherUI
     */
    public CipherUI() {
        initComponents();
        this.cipher = new Cipher();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        caeserInput = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        caeserShiftInput = new javax.swing.JTextField();
        caeserResultField = new javax.swing.JTextField();
        caeserEncodeButton = new javax.swing.JButton();
        caeserDecodeButton = new javax.swing.JButton();
        caeserBruteForceButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        vigenereInput = new javax.swing.JTextField();
        vigenereKeyInput = new javax.swing.JTextField();
        vigenereOutputPane = new javax.swing.JTextField();
        vigenereEncodeButton = new javax.swing.JButton();
        vigenereDecodeButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        autokeyInput = new javax.swing.JTextField();
        autokeyKey = new javax.swing.JTextField();
        autokeyResult = new javax.swing.JTextField();
        autokeyEncodeButton = new javax.swing.JButton();
        autokeyDecodeButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cipher");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        caeserInput.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                caeserInputActionPerformed(evt);
            }
        });

        jLabel1.setText("Message");

        jLabel2.setText("Shit Amount");

        caeserShiftInput.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                caeserShiftInputActionPerformed(evt);
            }
        });

        caeserResultField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                caeserResultFieldActionPerformed(evt);
            }
        });

        caeserEncodeButton.setText("Encode");
        caeserEncodeButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                caeserEncodeButtonActionPerformed(evt);
            }
        });

        caeserDecodeButton.setText("Decode");
        caeserDecodeButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                caeserDecodeButtonActionPerformed(evt);
            }
        });

        caeserBruteForceButton.setText("Brute Force");
        caeserBruteForceButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                caeserBruteForceButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Result");

        jLabel3.setText("<html>A Caeser Cipher, also known as a shift cipher, works by going <br> through the message letter by letter and shifting it up through the alphabet by the amount specified by the key number. For example, the message 'ABC' with a shift of 1 would become 'BCD'. If the shift reaches past 'Z' it wraps around and starts from the beginning of the alphabet.</html>");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(caeserEncodeButton)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(caeserResultField)
                            .addComponent(caeserShiftInput)
                            .addComponent(caeserInput)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(caeserBruteForceButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(caeserDecodeButton)))
                        .addGap(15, 15, 15))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(25, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(caeserInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caeserShiftInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(caeserResultField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caeserEncodeButton)
                    .addComponent(caeserDecodeButton)
                    .addComponent(caeserBruteForceButton))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Caeser", jPanel1);

        jLabel5.setText("Message");

        jLabel6.setText("Key");

        jLabel7.setText("Result");

        vigenereEncodeButton.setText("Encode");
        vigenereEncodeButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                vigenereEncodeButtonActionPerformed(evt);
            }
        });

        vigenereDecodeButton.setText("Decode");
        vigenereDecodeButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                vigenereDecodeButtonActionPerformed(evt);
            }
        });

        jLabel8.setText("<html>A Vigenere Cipher is a type of substitution cipher. It uses a table of alphabets, each one shifted cyclically to the left. It uses a different line from the table for each substitution, based on the letters of a repeating keyword.</html>");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(vigenereEncodeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 309, Short.MAX_VALUE)
                        .addComponent(vigenereDecodeButton))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(vigenereOutputPane)
                            .addComponent(vigenereKeyInput)
                            .addComponent(vigenereInput)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(vigenereInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(vigenereKeyInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(vigenereOutputPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vigenereEncodeButton)
                    .addComponent(vigenereDecodeButton))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Vigenere", jPanel7);

        jLabel9.setText("Message");

        jLabel10.setText("Key");

        jLabel11.setText("Result");

        autokeyEncodeButton.setText("Encode");
        autokeyEncodeButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                autokeyEncodeButtonActionPerformed(evt);
            }
        });

        autokeyDecodeButton.setText("Decode");
        autokeyDecodeButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                autokeyDecodeButtonActionPerformed(evt);
            }
        });

        jLabel12.setText("<html>The Autokey Cipher works a lot like a Vigenere Cipher in <br>the way that it substitutes letters using a tabula recta. The <br>difference is, as the name suggests, in the generation <br>of the key. In this cipher, the user still enters their own key, <br>but instead of this key being used over and over, the message is <br>tacked on to the end of the key. This way the message <br>itself is actually used as part of the key.</html>");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(autokeyEncodeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(autokeyDecodeButton))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(autokeyInput, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(autokeyKey)
                            .addComponent(autokeyResult)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(27, 27, 27))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(autokeyInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(autokeyKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(autokeyResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(autokeyEncodeButton)
                    .addComponent(autokeyDecodeButton))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Autokey", jPanel8);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void caeserInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caeserInputActionPerformed
        
    }//GEN-LAST:event_caeserInputActionPerformed

    private void caeserResultFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caeserResultFieldActionPerformed
        
    }//GEN-LAST:event_caeserResultFieldActionPerformed

    private void caeserEncodeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caeserEncodeButtonActionPerformed
        // Action for encode button
        String message = caeserInput.getText().toUpperCase();
        int offset = Integer.parseInt(caeserShiftInput.getText());
        caeserResultField.setText(this.cipher.encodeCaeser(message, offset));
    }//GEN-LAST:event_caeserEncodeButtonActionPerformed

    private void caeserDecodeButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_caeserDecodeButtonActionPerformed
    {//GEN-HEADEREND:event_caeserDecodeButtonActionPerformed
        try
        {
            String message = caeserInput.getText().toUpperCase();
            int offset = Integer.parseInt(caeserShiftInput.getText());
            caeserResultField.setText(this.cipher.decodeCaeser(message, offset));
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Please enter an integer for shift amount");
        }
    }//GEN-LAST:event_caeserDecodeButtonActionPerformed

    private void caeserBruteForceButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_caeserBruteForceButtonActionPerformed
    {//GEN-HEADEREND:event_caeserBruteForceButtonActionPerformed
        // brute force button
        StringBuilder output = new StringBuilder("Original: ");
        String message = caeserInput.getText().toUpperCase();
        output.append(message);
        output.append("\n\n");
        output.append(this.cipher.bruteForceCaeser(message));
        JOptionPane.showMessageDialog(null, output.toString());
    }//GEN-LAST:event_caeserBruteForceButtonActionPerformed

    private void vigenereEncodeButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_vigenereEncodeButtonActionPerformed
    {//GEN-HEADEREND:event_vigenereEncodeButtonActionPerformed
        // vigenere encode button
        String message = vigenereInput.getText().toUpperCase();
        String key = vigenereKeyInput.getText().toUpperCase();
        vigenereOutputPane.setText(cipher.encodeVigenere(message, key));
    }//GEN-LAST:event_vigenereEncodeButtonActionPerformed

    private void vigenereDecodeButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_vigenereDecodeButtonActionPerformed
    {//GEN-HEADEREND:event_vigenereDecodeButtonActionPerformed
        // vigenere decode button
        String message = vigenereInput.getText().toUpperCase();
        String key = vigenereKeyInput.getText().toUpperCase();
        vigenereOutputPane.setText(cipher.decodeVigenere(message, key));
    }//GEN-LAST:event_vigenereDecodeButtonActionPerformed

    private void autokeyDecodeButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_autokeyDecodeButtonActionPerformed
    {//GEN-HEADEREND:event_autokeyDecodeButtonActionPerformed
        String message = autokeyInput.getText().toUpperCase();
        String key = autokeyKey.getText().toUpperCase();
        autokeyResult.setText(cipher.decodeAutokey(message, key)); 
    }//GEN-LAST:event_autokeyDecodeButtonActionPerformed

    private void autokeyEncodeButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_autokeyEncodeButtonActionPerformed
    {//GEN-HEADEREND:event_autokeyEncodeButtonActionPerformed
        String message = autokeyInput.getText().toUpperCase();
        String key = autokeyKey.getText().toUpperCase();
        autokeyResult.setText(cipher.encodeAutokey(message, key));
    }//GEN-LAST:event_autokeyEncodeButtonActionPerformed

    private void caeserShiftInputActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_caeserShiftInputActionPerformed
    {//GEN-HEADEREND:event_caeserShiftInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caeserShiftInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CipherUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton autokeyDecodeButton;
    private javax.swing.JButton autokeyEncodeButton;
    private javax.swing.JTextField autokeyInput;
    private javax.swing.JTextField autokeyKey;
    private javax.swing.JTextField autokeyResult;
    private javax.swing.JButton caeserBruteForceButton;
    private javax.swing.JButton caeserDecodeButton;
    private javax.swing.JButton caeserEncodeButton;
    private javax.swing.JTextField caeserInput;
    private javax.swing.JTextField caeserResultField;
    private javax.swing.JTextField caeserShiftInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton vigenereDecodeButton;
    private javax.swing.JButton vigenereEncodeButton;
    private javax.swing.JTextField vigenereInput;
    private javax.swing.JTextField vigenereKeyInput;
    private javax.swing.JTextField vigenereOutputPane;
    // End of variables declaration//GEN-END:variables
}
